### ISSUE TITLE
Paper Review and Authorship Invitation

### ISSUE THREAD

**Issue by EiffL** [DifferentiableUniverseInitiative/jax-cosmo-paper#10]
The **paper draft** describing jax-cosmo and providing a few example use-cases for differentiable models is now **almost ready for submission** \o/ 
Thanks in large part to the efforts of @jecampagne and @joezuntz .

You can find the latest PDF version as an artifact in the latest run of [this action](https://github.com/DifferentiableUniverseInitiative/jax-cosmo-paper/actions/workflows/main.yml)

As per our initial [guidelines for authorship](https://github.com/DifferentiableUniverseInitiative/jax-cosmo-paper#guidelines-for-authorship) we would like to invite contributors to sign the current draft according to our two contributor tiers:  
  - First tier: (any) code contributions and paper writing (ordered by contributions)
  - Second tier: ideas and feedback (ordered alphabetically)

Please **send comments and sign up for authorship by Jan. 11th 2023**

## How to sign up for authorship

Open a Pull Request adding to the LaTeX document:

- Your name and institution here: 
https://github.com/DifferentiableUniverseInitiative/jax-cosmo-paper/blob/28dea870cd5f9175ec1a54786b8aab41996af417/paper_OJA.tex#L176
- A very brief contribution statement here:
https://github.com/DifferentiableUniverseInitiative/jax-cosmo-paper/blob/28dea870cd5f9175ec1a54786b8aab41996af417/paper_OJA.tex#L1056

Do not worry too much about the author order at this point, we will reorder once every body has signed up. Just **please indicate in your Pull Request if you would like to sign up in first or second tier**.

## How to submit comments and modifications

Please do not hesitate to open an issue with comments, and/or directly open a Pull Request to propose edits. If you would like to make significant edits/suggestions, don't hesitate to ask @EiffL for overleaf access if that is more convenient for you.

**Comment by EiffL** [comment]
**Note**: I will also be working hard to get any pending PR contributions merged in ASAP.

**Comment by santiagocasas** [comment]
@EiffL  @jecampagne   :  
I added directly to the overleaf both my name on the second tier and my (small) contribution at the end, as discussed with @EiffL .  Thanks for reminding me of this after a few weeks of not catching up with the changes.  
I am going through the latest additions of the paper and I have nothing else to say than congratulations for the great work, there is a lot of good material in there.

**Comment by EiffL** [comment]
Paper ready to submit \o/
