### ISSUE TITLE
Demonstrating Fisher  Forecasts

### ISSUE THREAD

**Issue by EiffL** [DifferentiableUniverseInitiative/jax-cosmo-paper#2]
I think one of the sections of the paper should illustrate how easy it is, and how stable it is to get Fisher matrices from a differentiable code.

This can be illustrated for instance by comparing Fishers of increasing complexity on a DES Y1 case compared to cosmosis.

**Comment by EiffL** [comment]
I've added a first draft of a notebook comparing Fisher forecasts for a DES Y1 analysis between jax-cosmo and CCL. Can be found here: 
https://github.com/DifferentiableUniverseInitiative/jax-cosmo-paper/blob/master/notebooks/Fisher.ipynb

For the moment, I've been able to find 2 things:
  - Discrepancy between `jax-cosmo` and CCL on number count cross correlations between first and last/second to last lens samples.
![image](https://user-images.githubusercontent.com/861591/88489884-b44a4900-cf97-11ea-9f7b-2509e879e7c4.png)

  - Instabilities in the gradient computation with finite differences (shocker I know) on the CCL side. For instance this is the gradient of shear shear spectra with respect to (A, eta) IA parameters with CCL:
![image](https://user-images.githubusercontent.com/861591/88489913-ee1b4f80-cf97-11ea-803f-8e85fb9eb46b.png)
There are weird large jumps, which, I can only assume, are due to failures to some integrals sometimes when CCL runs. This translates in a dramatic change of IA parameters contours:
![image](https://user-images.githubusercontent.com/861591/88489890-bf04de00-cf97-11ea-90ac-f565e5b2de02.png)

**Comment by joezuntz** [comment]
Maybe plot the derivatives as L dC_ell /  dp, with L as the Cholesky decomposition of the inverse covariance?  That would highlight which are the impactful changes.  Also it's often useful to plot (C_ell_CCL - C_ell_jax) / sigma to get a better idea of where the differences matter.
